### ISSUE TITLE
Cannot access "/root/.config/configstore/insight-yo.json" even as root

### ISSUE THREAD

**Issue by KuanHulio** [Microsoft/vscode-generator-code#111]
Running `Linux-3.10.0-693.21.1.el7.x86_64`

NPM Version: `4.2.0`
```
npm WARN deprecated formatio@1.2.0: This package is unmaintained. Use @sinonjs/formatio instead
/usr/bin/yo -> /usr/lib/node_modules/yo/lib/cli.js
/usr/bin/yo-complete -> /usr/lib/node_modules/yo/lib/completion/index.js

> yo@2.0.1 postinstall /usr/lib/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Everything looks all right!
/usr/lib
├── generator-code@1.1.29
└── yo@2.0.1```

Running `sudo yo code` (same thing happens whether or not sudo is ran or root):
```
/usr/lib/node_modules/yo/node_modules/insight/node_modules/configstore/index.js:53
                                throw err;
                                ^

Error: EACCES: permission denied, open '/root/.config/configstore/insight-yo.json'
You don't have access to this file.

    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at Configstore.get (/usr/lib/node_modules/yo/node_modules/insight/node_modules/configstore/index.js:34:26)
    at Configstore.get (/usr/lib/node_modules/yo/node_modules/insight/node_modules/configstore/index.js:81:13)
    at Insight.get (/usr/lib/node_modules/yo/node_modules/insight/lib/index.js:48:22)
    at Object.<anonymous> (/usr/lib/node_modules/yo/lib/cli.js:194:47)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)```

Steps taken to fix:

- chmod 777/755 /root/.config/configstore/insight-yo.json
- Root user chmod'ding

**Comment by reeversedev** [comment]
Hey this afternoon, I have been facing the same issue. Any luck with this issue so far?

**Comment by KuanHulio** [comment]
No, not really. I was using a Codenvy container. But I'm thinking it's due
to being a container that doesn't have files that it wants or a config

**Comment by reeversedev** [comment]
I found my fix though. What i did was really simple. I didn't log in as root user using sudo.
Rather, I tried entering the command with sudo as a prefix and it started running. Like: 
`sudo doanything`

**Comment by oscarrodar** [comment]
I went straight to the file and gave my user the read/write access and that fixed the issue 😄 

Hope it helps.
