### ISSUE TITLE
Trying to copy from a source that does not exist:  .../ext-command-js/jsconfig.json

### ISSUE THREAD

**Issue by sigoden** [Microsoft/vscode-generator-code#120]
Version:
```
+ yo@2.0.3
+ generator-code@1.1.34
```
Error Stack:
```
? What type of extension do you want to create? New Extension (JavaScript)
? What's the name of your extension? demo
? What's the identifier of your extension? demo
? What's the description of your extension?
? What's your publisher name (more info: https://code.visualstudio.com/docs/tools/vscecli#_publishing-extensions)? demo
? Enable JavaScript type checking in 'jsconfig.json'? Yes
? Initialize a git repository? No
events.js:183
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /home/xxx/.nvm/versions/node/v8.11.2/lib/node_modules/generator-code/generators/app/templates/ext-command-js/jsconfig.json
    at EditionInterface.exports._copySingle (/home/xxx/.nvm/versions/node/v8.11.2/lib/node_modules/generator-code/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/home/xxx/.nvm/versions/node/v8.11.2/lib/node_modules/generator-code/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (/home/xxx/.nvm/versions/node/v8.11.2/lib/node_modules/generator-code/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
    at constructor.template (/home/xxx/.nvm/versions/node/v8.11.2/lib/node_modules/generator-code/node_modules/yeoman-generator/lib/actions/actions.js:124:11)
    at constructor._writingCommandJs (/home/xxx/.nvm/versions/node/v8.11.2/lib/node_modules/generator-code/generators/app/index.js:693:14)
    at constructor.writing (/home/xxx/.nvm/versions/node/v8.11.2/lib/node_modules/generator-code/generators/app/index.js:542:22)
    at Object.<anonymous> (/home/xxx/.nvm/versions/node/v8.11.2/lib/node_modules/generator-code/node_modules/yeoman-generator/lib/base.js:439:23)
    at /home/xxx/.nvm/versions/node/v8.11.2/lib/node_modules/generator-code/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /home/xxx/.nvm/versions/node/v8.11.2/lib/node_modules/generator-code/node_modules/run-async/index.js:24:19
```
Why:

The `jsconfig.json` is ignored by `.npmignore`

**Comment by crstamps2** [comment]
Rolling back to version 1.1.32 also worked. I chose that one by chance since the last two releases were done on the same day.

**Comment by bpasero** [comment]
I also get this @aeschli 

![image](https://user-images.githubusercontent.com/900690/42395431-384a7fca-815e-11e8-8f46-4948e4709b86.png)

**Comment by LevitatingBusinessMan** [comment]
[jsconfig.json](https://github.com/Microsoft/vscode-generator-code/blob/595341d5e3c8c4feeb386c5141e96da2ff67f1a5/.npmignore#L9)  got added to .npmignore in commit db70d7c

**Comment by bpasero** [comment]
I pushed https://github.com/Microsoft/vscode-generator-code/commit/920c825239b5a120d59c9e6322f80b038f667de3 as workaround. It should work fine again with `generator-code@1.1.35`
