### ISSUE TITLE
Error on running generator-code

### ISSUE THREAD

**Issue by tmarunagiri** [Microsoft/vscode-generator-code#128]
yo code has generated the below given error. Any Idea how to resolve this. I am using V1.1.37

AppData\Roaming\npm\node_modules\generator-code\generators\app\index.js:47
    async prompting() {
          ^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.get [as code:app] (\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:39:27)
    at Store.get (\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:62:39)

**Comment by tmarunagiri** [comment]
This is because async is not supported by lower version of node.  Either need to transpile using babel or install latest version of node
