### ISSUE TITLE
TypeError when running yo code

### ISSUE THREAD

**Issue by VoxlDavid** [Microsoft/vscode-generator-code#151]
after having installed yo and generator-code globally i get this error when running yo code or when selecting the generator from yeoman's menu:

```

C:\Users\voxld\AppData\Roaming\npm\node_modules\generator-code\node_modules\errlop\index.js:4
module.exports = require('editions').requirePackage(__dirname, require)
                                     ^
TypeError: require(...).requirePackage is not a function
    at Object.<anonymous> (C:\Users\voxld\AppData\Roaming\npm\node_modules\generator-code\node_modules\errlop\index.js:4:38)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\voxld\AppData\Roaming\npm\node_modules\generator-code\node_modules\editions\edition-node-0.8\index.js:12:14)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
```

I've tried multiple node versions but it doesn't work at all for me

OS: Windows 10
NodeJS: Current Latest and Current LTS

**Comment by VoxlDavid** [comment]
Hm, after using `yo` to 'Update Generators' it works... well I guess there was some outdated conflicts or something...
