### ISSUE TITLE
"yo code" fails with TypeError

### ISSUE THREAD

**Issue by RichardMisiak** [Microsoft/vscode-generator-code#167]
Steps to reproduce

1. Install generator as per instructions with ` npm install -g yo generator-code`
2. Run `yo code`

Fails for me with this error:
```
C:\Users\Richard\AppData\Roaming\npm\node_modules\yo\node_modules\conf\index.js:69
                        throw new TypeError('Use `delete()` to clear values');
                        ^

TypeError: Use `delete()` to clear values
    at Conf.set (C:\Users\Richard\AppData\Roaming\npm\node_modules\yo\node_modules\conf\index.js:69:10)
    at Insight.set optOut [as optOut] (C:\Users\Richard\AppData\Roaming\npm\node_modules\yo\node_modules\insight\lib\index.js:56:15)
    at Object.<anonymous> (C:\Users\Richard\AppData\Roaming\npm\node_modules\yo\lib\cli.js:198:18)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
```

Windows 10 Latest
npm version 6.4.1
node version 10.12.0

Output from npm install
```
$ npm install -g yo generator-code
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
C:\Users\Richard\AppData\Roaming\npm\yo-complete -> C:\Users\Richard\AppData\Roaming\npm\node_modules\yo\lib\completion\index.js
C:\Users\Richard\AppData\Roaming\npm\yo -> C:\Users\Richard\AppData\Roaming\npm\node_modules\yo\lib\cli.js

> spawn-sync@1.0.15 postinstall C:\Users\Richard\AppData\Roaming\npm\node_modules\yo\node_modules\spawn-sync
> node postinstall


> yo@2.0.5 postinstall C:\Users\Richard\AppData\Roaming\npm\node_modules\yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ Node.js version
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory
√ npm version
√ yo version

Everything looks all right!
+ yo@2.0.5
+ generator-code@1.1.50
added 926 packages from 312 contributors in 33.198s

```

**Comment by RichardMisiak** [comment]
Noticed that this error occurs when running `yo` by itself, so isn't specific to this generator
