### ISSUE TITLE
TypeScript HelloWorld does not work

### ISSUE THREAD

**Issue by zdrummond** [microsoft/vscode-generator-code#182]
MacOs 10.14.6
Node 11.9
nom 6.9.0
VS Code 1.38.1

----

Hello. New to both typescript and VS extensions. I just grabbed the yeoman and followed the Hello World steps. 

When I go for TypeScript I get the follow error;

(`<snip>` is removing PII, but is just my home dir path)
```
(node:78681) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Activating extension `fernandoescolar.vscode-solution-explorer` failed:  The "path" argument must be of type string. Received type undefined
Here is the error stack:  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1155:7)
    at new TemplateEngine ('<snip>/.vscode/extensions/fernandoescolar.vscode-solution-explorer-0.3.5/out/extension.js:2:29208)
    at new module.exports.t.SolutionExplorerProvider ('<snip>/.vscode/extensions/fernandoescolar.vscode-solution-explorer-0.3.5/out/extension.js:1:100983)
    at module.exports.t.activate ('<snip>/.vscode/extensions/fernandoescolar.vscode-solution-explorer-0.3.5/out/extension.js:1:98442)
    at Function._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:656:440)
    at Function._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:656:91)
    at A._doActivateExtension.Promise.all.then.i (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:655:131)
Looking for parseable documents...
Found no documents
Activating extension `undefined_publisher.helloworld` failed:  Cannot find module ''<snip>/helloworld/out/extension.js'
Here is the error stack:  Error: Cannot find module '<snip>/helloworld/out/extension.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:588)
    at Function.define._installInterceptor.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:751:448)
    at Function.t.getExtensionPathIndex.then.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:742:925)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Function.i [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:32:381)
    at f._loadCommonJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:752:632)
    at f._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:655:27)
    at f._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:654:108)
    at f.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:651:937)
    at Generator.next (<anonymous>)
    at i (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:14:83)
    at new Promise (<anonymous>)
    at i (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:13:862)
    at Object.actualActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:651:639)
    at p._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:497:21)
    at define._activateExtensions.r.length.Promise.all.s.map.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:496:628)
    at Array.map (<anonymous>)
    at p._activateExtensions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:496:616)
    at p.activateByEvent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:494:477)
    at f._activateByEvent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:652:775)
    at A.$activateByEvent._readyToRunExtensions.wait.then.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:661:547)
```

When I follow the steps for `New Extension (JavaScript)` things work and the "Hello World" snack bar shows up.

**Comment by aeschli** [comment]
out/extension.js is not there. It look like it was not built.
Can you run `npm run compile` and  see if there's a problem?

**Comment by zdrummond** [comment]
That appeared to work, although I still get some error/warning messages. 

```
(node:6474) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Activating extension `fernandoescolar.vscode-solution-explorer` failed:  The "path" argument must be of type string. Received type undefined
Here is the error stack:  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1155:7)
    at new TemplateEngine (<snip>/.vscode/extensions/fernandoescolar.vscode-solution-explorer-0.3.5/out/extension.js:2:29208)
    at new module.exports.t.SolutionExplorerProvider (/Users/zdrummond/.vscode/extensions/fernandoescolar.vscode-solution-explorer-0.3.5/out/extension.js:1:100983)
    at module.exports.t.activate (<snip>/.vscode/extensions/fernandoescolar.vscode-solution-explorer-0.3.5/out/extension.js:1:98442)
    at Function._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:656:440)
    at Function._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:656:91)
    at A._doActivateExtension.Promise.all.then.i (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:655:131)
```

So how do we make it automatically compile. 

The docs say; "Then, inside the editor, press F5. This will compile and run the extension in a new Extension Development Host window."

**Comment by aeschli** [comment]
Can you run npm run compile and see if there's a problem?

Yes, on F5, we run the launch configuration that also triggers `npm run watch`.

**Comment by zdrummond** [comment]
@aeschli If I run the script task inside VS Code for `watch` it returns a error code of 1 with no output. 

If I do it for `compile` it returns 

```
> Executing task: npm run compile <

internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
Require stack:
- /usr/local/lib/node_modules/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:152:3)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/npm/bin/npm-cli.js' ]
}
The terminal process terminated with exit code: 1
```

I agree with it, I don't have `'../lib/utils/unsupported.js'` but I also don't know why it's looking for it, and if I run either `npm run compile` or `watch` on the terminal it all works great.

**Comment by aeschli** [comment]
@zdrummond It looks like your installation of 'npm' (included with node) has a problem.

See https://stackoverflow.com/questions/44363066/error-cannot-find-module-lib-utils-unsupported-js-while-using-ionic

**Comment by aisuandebowen** [comment]
> 
It solve my question, but why not add reminders or step to the official website.

**Comment by aisuandebowen** [comment]
> Can you run `npm run compile` and see if there's a problem?
> 
> Yes, on F5, we run the launch configuration that also triggers `npm run watch`.

It solved my question, but why not add reminders or step to the official website?
