### ISSUE TITLE
Instll:Error: Couldn't find the 'yo' binary. 

### ISSUE THREAD

**Issue by BackMountainDevil** [microsoft/vscode-generator-code#228]
npm 6.14.8
node v14.15.0
OS: Deepin 20
Hareware: Lenove Xiaoxin13 Pro AMD 2020

I dowm npm  from official web. When I tried to install yo it got some problem"Error: Couldn't find the 'yo' binary. "
# npm

```bash
$ sudo mv node-v14.15.0-linux-x64 /opt/nodejs

$ sudo ln -s /opt/nodejs/bin/npm /usr/local/bin/
$ sudo ln -s /opt/nodejs/bin/node /usr/local/bin/

$ sudo npm config set registry https://registry.npm.taobao.org
npm config set registry https://mirrors.huaweicloud.com/repository/npm/
```
# yo
Here comes the Error
```bash
$ npm install -g yo generator-code
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
/opt/nodejs/bin/yo -> /opt/nodejs/lib/node_modules/yo/lib/cli.js
/opt/nodejs/bin/yo-complete -> /opt/nodejs/lib/node_modules/yo/lib/completion/index.js

> ejs@2.7.4 postinstall /opt/nodejs/lib/node_modules/generator-code/node_modules/yeoman-environment/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> core-js@3.7.0 postinstall /opt/nodejs/lib/node_modules/yo/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> ejs@2.7.4 postinstall /opt/nodejs/lib/node_modules/yo/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> spawn-sync@1.0.15 postinstall /opt/nodejs/lib/node_modules/yo/node_modules/spawn-sync
> node postinstall


> yo@3.1.1 postinstall /opt/nodejs/lib/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ No .bowerrc file in home directory
✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ No .yo-rc.json file in home directory
✔ Node.js version
✔ npm version
Error: Couldn't find the 'yo' binary. Make sure it's installed and in your $PATH
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn yo',
  path: 'yo',
  spawnargs: [ '--version' ],
  cmd: 'yo --version'
}
✖ yo version
Error: Couldn't find the 'yo' binary. Make sure it's installed and in your $PATH
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn yo',
  path: 'yo',
  spawnargs: [ '--version' ],
  cmd: 'yo --version'
}

Found potential issues on your machine :(
+ yo@3.1.1
+ generator-code@1.3.7
added 1168 packages from 397 contributors in 213.861s
```
Then I type `yo --version` return failure.
Here is my solution
## Test
```bash
$ yo --version
```
It did not show the version
## Fixbug
```bash
$ whereis yo
yo: /opt/nodejs/bin/yo
$ cd /opt/nodejs/bin/
$ ./yo --version
3.1.1   
$ sudo ln -s /opt/nodejs/bin/yo /usr/local/bin/
```
Then it works. It is a little wired, though it finally works.

**Comment by aeschli** [comment]
Not sure what the issue is, likely a npm problem, but not the yo code generator...
