### ISSUE TITLE
Web integration tests timing out and failing

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-generator-code#293]
<details>

```
integration tests
    1) command-ts integration test (install, compile and run extension tests)
    ✓ command-ts-webpack integration test (install, pack and run extension tests) (20320ms)
    2) command-ts-web integration test (install, pack and run extension tests)

  test code generator
    expecting engine version ^1.58.0
    ✓ theme import (1992ms)
    ✓ theme import from file (154ms)
    ✓ theme import from file - issue 74 (108ms)
    ✓ theme new (108ms)
    ✓ language import (383ms)
    ✓ language import 2 (83ms)
    ✓ language new (75ms)
    ✓ snippet new (118ms)
    ✓ snippet import (90ms)
    ✓ keymap new (202ms)
    ✓ command-ts (197ms)
    ✓ command-ts with yarn (147ms)
    ✓ command-ts with webpack (182ms)
    ✓ command-js (219ms)
    ✓ command-js with check JS (108ms)
    ✓ extension-pack (132ms)
    ✓ language pack (139ms)
    ✓ language pack with yarn (104ms)
    ✓ command-web (188ms)
    ✓ sample notebook renderer (414ms)


  21 passing (2m)
  2 failing

  1) integration tests
       command-ts integration test (install, compile and run extension tests):
     Error: Command failed with exit code 1: npm run test
[main 2021-08-03T18:28:25.274Z] Running extension tests from the command line is currently only supported if no other instance of Code is running.

[main 2021-08-03T18:28:25.277Z] Error: Running extension tests from the command line is currently only supported if no other instance of Code is running.
    at se.claimInstance (/private/var/folders/68/j08r_6yx1dbf7h8kbvnhgbhm0000gn/T/78d35cd8ecc9367642f5abdfe1714006f0e6ad58/testCom/.vscode-test/vscode-darwin-1.58.2/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:61:4960)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /private/var/folders/68/j08r_6yx1dbf7h8kbvnhgbhm0000gn/T/78d35cd8ecc9367642f5abdfe1714006f0e6ad58/testCom/.vscode-test/vscode-darwin-1.58.2/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:61:2029
    at async se.startup (/private/var/folders/68/j08r_6yx1dbf7h8kbvnhgbhm0000gn/T/78d35cd8ecc9367642f5abdfe1714006f0e6ad58/testCom/.vscode-test/vscode-darwin-1.58.2/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:61:1899)

Failed to run tests
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testCom@0.0.1 test: `node ./out/test/runTest.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the testCom@0.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tanha/.npm/_logs/2021-08-03T18_28_25_314Z-debug.log

> testCom@0.0.1 pretest /private/var/folders/68/j08r_6yx1dbf7h8kbvnhgbhm0000gn/T/78d35cd8ecc9367642f5abdfe1714006f0e6ad58/testCom
> npm run compile && npm run lint


> testCom@0.0.1 compile /private/var/folders/68/j08r_6yx1dbf7h8kbvnhgbhm0000gn/T/78d35cd8ecc9367642f5abdfe1714006f0e6ad58/testCom
> tsc -p ./


> testCom@0.0.1 lint /private/var/folders/68/j08r_6yx1dbf7h8kbvnhgbhm0000gn/T/78d35cd8ecc9367642f5abdfe1714006f0e6ad58/testCom
> eslint src --ext ts


> testCom@0.0.1 test /private/var/folders/68/j08r_6yx1dbf7h8kbvnhgbhm0000gn/T/78d35cd8ecc9367642f5abdfe1714006f0e6ad58/testCom
> node ./out/test/runTest.js

Downloading VS Code 1.58.2 from https://update.code.visualstudio.com/1.58.2/darwin/stableDownloaded VS Code 1.58.2 into /private/var/folders/68/j08r_6yx1dbf7h8kbvnhgbhm0000gn/T/78d35cd8ecc9367642f5abdfe1714006f0e6ad58/testCom/.vscode-test/vscode-darwin-1.58.2
Exit code:   1
Done

      at makeError (node_modules/execa/lib/error.js:59:11)
      at Function.module.exports.sync (node_modules/execa/index.js:188:17)
      at /Users/tanha/Documents/GitHub/msft-vscode-generator-code/test/test-integration.js:31:36

  2) integration tests
       command-ts-web integration test (install, pack and run extension tests):
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/tanha/Documents/GitHub/msft-vscode-generator-code/test/test-integration.js)
      at /Users/tanha/Documents/GitHub/msft-vscode-generator-code/test/test-integration.js:100:17



npm ERR! Test failed.  See above for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! generator-code@1.5.6 preversion: `npm test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the generator-code@1.5.6 preversion script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tanha/.npm/_logs/2021-08-03T18_29_51_307Z-debug.log
```

</details>

**Comment by aeschli** [comment]
Did you see the warning 'Running extension tests from the command line is currently only supported if no other instance of Code is running? Could that be the problem? We run the extension with stable code, so that one can't run.

**Comment by tanhakabir** [comment]
Hm where should I look for the warning? I don't see any warning right now.

Right now I tried running `npm test` without any instances of VS Code running (insiders and stable) but now it's been stuck  (for about 30 min) after launching an instance of Chromium with a blank screen.

**Comment by aeschli** [comment]
Make sure to use `@vscode/test-web@0.8.0)...

**Comment by tanhakabir** [comment]
as in make sure my dependencies are properly installed?

**Comment by aeschli** [comment]
Sorry, foger about ``@vscode/test-web@0.8.0)`, that's part of env.js and I updated that.

I just increased the timeout, maybe that helps.
If you can try again from the latest in main (also run `npm install`).
