### ISSUE TITLE
code generator for new language returns "languageFileName is not defined" error

### ISSUE THREAD

**Issue by Ikkyu-os** [Microsoft/vscode-generator-code#31]
Hello

I have been trying to play with your editor for new languages, but can't make it work unfortunately.

I used the option "new language support" with following data:
```
? What type of extension do you want to create? New Language Support
URL (http, https) or file name of the tmLanguage file, e.g., http://raw.githubusercontent.com/textmate/ant.tmbundle/master/Syntaxes/Ant.tmLanguage.
? URL or file: https://github.com/ariatemplates/sublime-ariatemplates-highlighter/blob/master/Aria%20Templates.tmLanguage
? URL or file: https://github.com/ariatemplates/editors-tools/blob/master/subli
languageFileName raw = N-tmLanguage
? What's the name of your extension? at
? What's the name of your extension? at
? What's the identifier of your extension? (at) at
? What's the identifier of your extension? at
? What's the description of your extension? at desc
? What's the description of your extension? at desc
? What's your publisher name? (test) attest
? What's your publisher name? attest
Verify the id of the language. The id is an identifier and is single, lower-case name such as 'php', 'javascript'
? Detected languageId: () ariatemplates
? Detected languageId: ariatemplates
Verify the name of the language. The name will be shown in the VS code editor mode selector.
? Detected name: () ariatemplates
? Detected name: ariatemplates
Verify the file extensions of the language. Use commas to separate multiple entries (e.g. .ruby, .rb)
? Detected file extensions: () .tpl
? Detected file extensions: .tpl
```

and i get the following error:
```
languageFileName is not defined
    at eval (eval at <anonymous> (C:\Users\rblineau\AppData\Roaming\npm\node_modules\generator-code\node_modules\ejs\lib\ejs.js:485:12), <anonymous>:11:23)
    at returnedFn (C:\Users\rblineau\AppData\Roaming\npm\node_modules\generator-code\node_modules\ejs\lib\ejs.js:514:17)
    at Object.exports.render (C:\Users\rblineau\AppData\Roaming\npm\node_modules\generator-code\node_modules\ejs\lib\ejs.js:316:37)
    at copy.process (C:\Users\rblineau\AppData\Roaming\npm\node_modules\generator-code\node_modules\mem-fs-editor\actions\copy-tpl.js:14:18)
    at applyProcessingFunc (C:\Users\rblineau\AppData\Roaming\npm\node_modules\generator-code\node_modules\mem-fs-editor\actions\copy.js:13:16)
    at EditionInterface.exports._copySingle (C:\Users\rblineau\AppData\Roaming\npm\node_modules\generator-code\node_modules\mem-fs-editor\actions\copy.js:51:16)
    at EditionInterface.exports.copy (C:\Users\rblineau\AppData\Roaming\npm\node_modules\generator-code\node_modules\mem-fs-editor\actions\copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (C:\Users\rblineau\AppData\Roaming\npm\node_modules\generator-code\node_modules\mem-fs-editor\actions\copy-tpl.js:12:8)
    at template (C:\Users\rblineau\AppData\Roaming\npm\node_modules\generator-code\node_modules\yeoman-generator\lib\actions\actions.js:134:11)
    at module.exports.yeoman.generators.Base.extend._writingLanguage (C:\Users\rblineau\AppData\Roaming\npm\node_modules\generator-code\generators\app\index.js:565:10)
```

I tried to analyze a bit why filename would be missing, but without success for now.
Is it a known issue or perhaps my system setup is not inline with the tool ?

**Comment by Ikkyu-os** [comment]
I'll close because I figure out my mistake.


In the end, my issue was linked to me using an url as this one:
https://github.com/ariatemplates/sublime-ariatemplates-highlighter/blob/master/Aria%20Templates.tmLanguage
Which doesn't return directly the template file.
