### ISSUE TITLE
TypeError: Object.fromEntries is not a function

### ISSUE THREAD

**Issue by antoninhrlt** [microsoft/vscode-generator-code#343]
I followed this article : https://code.visualstudio.com/api/get-started/your-first-extension 
but when I tried to execute the yo code generator, it raised an error.

Executed command : `$ yo code`

Output error :
```
/usr/local/lib/node_modules/yo/node_modules/npm-registry-fetch/node_modules/@npmcli/fs/lib/fs.js:6
const fsSync = Object.fromEntries(Object.entries(fs).filter(([k, v]) =>
                      ^

TypeError: Object.fromEntries is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/node_modules/npm-registry-fetch/node_modules/@npmcli/fs/lib/fs.js:6:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/node_modules/npm-registry-fetch/node_modules/@npmcli/fs/lib/index.js:2:6)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

NodeJS version : `v10.19.0`

**Comment by nhedger** [comment]
The latest version of the `yo` package [supports node `>=12.10.0`](https://github.com/yeoman/yo/blob/v4.3.0/package.json#L15). 

Your node version `10.19.0` is therefore too old to run it.

I suggest you update your node version and try again.

**Comment by antoninhrlt** [comment]
I followed this article : https://computingforgeeks.com/how-to-install-nodejs-on-ubuntu-debian-linux-mint/
And then, it works
