### ISSUE TITLE
Error when /home/node_modules is not readable

### ISSUE THREAD

**Issue by rtomson** [Microsoft/vscode-generator-code#44]
If /home/node_modules does not exist, you do not get this error. This only occurs when the directory exists but is not readable by the current user.

Why is it looking for this home directory to begin with? In sites with network home directories, it will try and mount /home/node_modules as well as /home/.yo-rc.json

```
/usr/lib/node_modules/yo/node_modules/glob/sync.js:321
        throw er
              ^
Error: EACCES, permission denied '/home/node_modules'
    at Object.fs.readdirSync (fs.js:666:18)
    at GlobSync._readdir (/usr/lib/node_modules/yo/node_modules/glob/sync.js:275:41)
    at GlobSync._processReaddir (/usr/lib/node_modules/yo/node_modules/glob/sync.js:135:22)
    at GlobSync._process (/usr/lib/node_modules/yo/node_modules/glob/sync.js:130:10)
    at new GlobSync (/usr/lib/node_modules/yo/node_modules/glob/sync.js:46:10)
    at Function.globSync [as sync] (/usr/lib/node_modules/yo/node_modules/glob/sync.js:24:10)
    at /usr/lib/node_modules/yo/node_modules/globby/index.js:55:35
    at Array.reduce (native)
    at Function.module.exports.sync (/usr/lib/node_modules/yo/node_modules/globby/index.js:54:19)
    at /usr/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:71:22
```

**Comment by aeschli** [comment]
This sounds like an issue to file against the yeoman generator: http://yeoman.io/contributing/
