### ISSUE TITLE
VSCode running "yo code" gives me an ERR_INVALID_ARG_TYPE error

### ISSUE THREAD

**Issue by ochtum** [microsoft/vscode-generator-code#488]
```
PS C:\Users\{username}> yo code

     _-----_     ╭──────────────────────────╮
    |       |    │   Welcome to the Visual  │
    |--(o)--|    │   Studio Code Extension  │
   `---------´   │        generator!        │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? What type of extension do you want to create? New Extension (TypeScript)
? What's the name of your extension? test
? What's the identifier of your extension? test
? What's the description of your extension?
? Initialize a git repository? Yes
? Which bundler to use? unbundled
? Which package manager to use? yarn

Writing in C:\Users\{username}\test...
✖️ An error occured while running code:app#writing
Error code

Trying to copy from a source that does not exist: C:\Users\{username}\AppData\Roaming\npm\node_modules\generator-code\generators\app\templates\ext-command-ts\vscode
TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received type string ('ERR_ASSERTION')
    at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
    at process.exit (node:internal/process/per_thread:180:24)
    at onError (C:\Users\{username}\AppData\Roaming\npm\node_modules\yo\lib\cli.js:117:11)
    at C:\Users\{username}\AppData\Roaming\npm\node_modules\yo\lib\cli.js:168:54
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async init (C:\Users\{username}\AppData\Roaming\npm\node_modules\yo\lib\cli.js:168:5)
    at async pre (C:\Users\{username}\AppData\Roaming\npm\node_modules\yo\lib\cli.js:83:3)
    at async C:\Users\{username}\AppData\Roaming\npm\node_modules\yo\lib\cli.js:193:3
```
I am running it as described in Your First Extension in VS Code's GET STARTED, but it keeps reproducing even after reinstalling node.js.

Additional information
OS: Windows 11
Terminal: powershell
Generator Location: C:\Users{username}\AppData\Roaming\npm\node_modules\generator-code
node:v20.17.0

reinstalling node.js.
delete folder:C:\Users{username}\AppData\Roaming\npm

**Comment by CarlosEGuerraSilva** [comment]
Same issue here, :/

**Comment by ochtum** [comment]
I resolved the issue myself.
You can fix it by following the steps below:
1. Move the `[yo]` folder and `[generator-code]` folder from the following directory to a desired location:
C:\Users\{UserName}\AppData\Roaming\npm\node_modules

2. Edit the `$basedir` in the following file to the path of the new location:
C:\Users\{UserName}\AppData\Roaming\npm\yarn.ps1

```
#$basedir=Split-Path $MyInvocation.MyCommand.Definition -Parent
$basedir="new path"
```
