### ISSUE TITLE
Cannot use yo code under wsl

### ISSUE THREAD

**Issue by alaric8** [microsoft/vscode-generator-code#495]
yo code                                                                                                    [8m]
node:internal/modules/cjs/loader:1251
  throw err;
  ^

Error: Cannot find module 'is-ci'
Require stack:
- /root/.local/share/fnm/node-versions/v22.8.0/installation/lib/node_modules/yo/node_modules/update-notifier/index.js
- /root/.local/share/fnm/node-versions/v22.8.0/installation/lib/node_modules/yo/lib/cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1248:15)
    at Module._load (node:internal/modules/cjs/loader:1074:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1339:12)
    at require (node:internal/modules/helpers:135:16)
    at lazy (/root/.local/share/fnm/node-versions/v22.8.0/installation/lib/node_modules/yo/node_modules/import-lazy/index.js:2:51)
    at /root/.local/share/fnm/node-versions/v22.8.0/installation/lib/node_modules/yo/node_modules/import-lazy/index.js:10:11
    at new UpdateNotifier (/root/.local/share/fnm/node-versions/v22.8.0/installation/lib/node_modules/yo/node_modules/update-notifier/index.js:46:4)
    at module.exports (/root/.local/share/fnm/node-versions/v22.8.0/installation/lib/node_modules/yo/node_modules/update-notifier/index.js:183:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/.local/share/fnm/node-versions/v22.8.0/installation/lib/node_modules/yo/node_modules/update-notifier/index.js',
    '/root/.local/share/fnm/node-versions/v22.8.0/installation/lib/node_modules/yo/lib/cli.js'
  ]
}

Node.js v22.8.0

**Comment by aeschli** [comment]
I can't reproduce. `yo code` works for me also on WSL.

The stacktrace shows that's a problem in `yo`: https://github.com/yeoman/yeoman/issues/1773

Maybe try with a different node version? The one I used is 20.15.0?
