### ISSUE TITLE
vscode not found

### ISSUE THREAD

**Issue by InTheCloudDan** [Microsoft/vscode-generator-code#82]
I used `yo code` to generate a javascript extension when I go to launch debug mode it throws:

```
Error: Cannot find module 'vscode'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/danielobrien/Projects/randomName/randomname/src/extension.js:3:14)
    at Module._compile (module.js:566:14)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

node: v8.1.3
npm: 5.0.3
VS Code: 1.13.1

**Comment by InTheCloudDan** [comment]
Figured out my issue, I tried to open folder manually and not launch with the `code .` guessing there's some environment set there.
